matrix:
    include:
      - language: go
        go: 
            - 1.14.x
        os:
            - linux
        script:
            - "cd golang"
            - "make build"
      - language: dart
        dart:
            - stable
        script:
            - dart Dart/gol_test.dart    
